### ISSUE TITLE
liboca does not link CoreFoundation,IOKit,-lobjc on OSX

### ISSUE THREAD

**Issue by maartentamboer** [Open-Canalyzer/liboca#5]
libusb needs these frameworks, otherwise linking errors will occur when linking an executable.

See https://sourceforge.net/p/libusb/mailman/libusb-devel/thread/21C5EBE5-5469-45E9-B3B4-B44248F58855@kernel.crashing.org/ 

    target_link_libraries(nanopb_test "-framework CoreFoundation")
    target_link_libraries(nanopb_test "-framework IOKit")
    target_link_libraries(nanopb_test "-lobjc")

**Comment by xor-gate** [comment]
Better do something different:

https://github.com/xor-gate/stlink2/blob/4d6c10e91589bd55cba7cf97e2e2b3e90037c8f5/src/CMakeLists.txt#L49-L56
